# Generated by Django 6.0.4 on 2026-04-20 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'URL / Ссылка'), ('apk', 'APK Файл')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('scanning', 'Сканирование'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='apk_uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file_hash_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('vt_scan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vt_permalink', models.URLField(blank=True, max_length=512, null=True)),
                ('malicious_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('harmless_count', models.IntegerField(default=0)),
                ('undetected_count', models.IntegerField(default=0)),
                ('total_engines', models.IntegerField(default=0)),
                ('is_phishing', models.BooleanField(blank=True, null=True)),
                ('threat_label', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Результат сканирования',
                'verbose_name_plural': 'Результаты сканирований',
                'ordering': ['-created_at'],
            },
        ),
    ]
